/**/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    # joint_state_controller:
    #   type: joint_state_controller/JointStateController

    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
      
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# /**/joint_state_controller:
/**/joint_group_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
    interface_name: position
    gains:
        p: 100.0
        i: 0.0
        d: 10.0
    state_publish_rate: 25
    # command_interfaces:
    #   - effort
    # state_interfaces:
    #   - position
    #   - velocity
