<?xml version="1.0"?>
<robot
    xmlns:xacro="http://www.ros.org/wiki/xacro" name="hydrus" >

  <!-- basic kinematics model -->
  <m_f_rate value="-0.0182" /> <!-- overwrite -->
  <xacro:include filename="$(find hydrus)/urdf/common.xacro" />
  <xacro:include filename="$(find hydrus)/urdf/link.urdf.xacro" />

  <xacro:hydrus_link links="4" self="1" rotor_direction="-1" with_battery = "0" old_version = "1" />
  <xacro:hydrus_link links="4" self="2" rotor_direction="1"  with_battery = "0" old_version = "1" />
  <xacro:hydrus_link links="4" self="3" rotor_direction="-1" with_battery = "0" old_version = "1" />
  <xacro:hydrus_link links="4" self="4" rotor_direction="1"  with_battery = "0" old_version = "1" />

  <!-- special battery arrangement -->
  <xacro:extra_module name = "bat1" parent = "link1" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" scale="0.001">
    <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.4108"/>
      <inertia
          ixx="0.0001" iyy="0.0006" izz="0.0006"
          ixy="0.0" ixz="0.0"  iyz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <xacro:extra_module name = "bat2" parent = "link4" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/battery/Kypom-3000-6s.dae" scale="0.001">
    <origin xyz="${link_length/2} 0.0 -0.048" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="0.4108"/>
      <inertia
          ixx="0.0001" iyy="0.0006" izz="0.0006"
          ixy="0.0" ixz="0.0"  iyz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <!-- onboard -->
  <!-- 1.  processor -->
  <!-- 1.1 flight controller -->
  <xacro:extra_module name = "fc" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/ver1/flight_controller/fc_euclid201806.dae"> <!-- same with intel euclid -->
    <origin xyz="${link_length / 2 + 0.2281} ${-4.4*0.001} 0.03533" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.05" />
      <origin xyz="${11.48*0.001} ${4.3*0.001} ${-9.4*0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.00001" ixy="0.0" ixz="0.0"
          iyy="0.00001" iyz="0.0"
          izz="0.00002"/>
    </inertial>
  </xacro:extra_module>

  <!-- end: flight controller -->

  <!-- 1.2 processor: jetson tx2 -->
  <xacro:extra_module name = "pc" parent = "link3" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/ver1/processor/jetson_tx2.dae"
                      scale="0.001" >
    <origin xyz="0.086 0.0 ${-0.0192}" rpy="0 0 ${pi}"/>
    <inertial>
      <mass value = "0.181" />
      <origin xyz="0 ${-5 * 0.001} 0" rpy="0 0 0"/>
      <inertia
          ixx="0.00001" ixy="0.0" ixz="0.0"
          iyy="0.00001" iyz="0.0"
          izz="0.00001"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: processor: jetson tx2 -->

  <!-- 2.  sensor -->
  <!-- 2.1 leddar one -->
  <xacro:extra_module name = "leddarone" parent = "link3" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/sensor/leddar_one_tx2_attached_mode.dae">
    <origin xyz="0.0866 0.0 -0.06267" rpy="0 ${pi} 0"/>
    <inertial>
      <origin xyz="-0.007950 0.000000 -0.000140" rpy="0 0 0"/>
      <mass value="0.029000"/>
      <inertia
          ixx="0.000010" iyy="0.000008" izz="0.000008"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
  </xacro:extra_module>
  <!-- end: leddar one -->

  <!-- 2.2 gps -->
  <xacro:extra_module name = "gps" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/sensor/gps_ublox_m8n.dae">
    <origin xyz="${link_length/2 + 0.1925} 0.0 0.152" rpy="0 0 0"/>
    <inertial>
      <origin xyz="0.000000 0.000000 -0.062510" rpy="0 0 0"/>
      <mass value="0.053000"/>
      <inertia
          ixx="0.000503" iyy="0.000503" izz="0.000010"
          ixy="0.000000" ixz="0.000000" iyz="0.000000"/>
    </inertial>
  </xacro:extra_module>
  <xacro:extra_module name = "magnet" parent = "gps">
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.00001" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.000001" ixy="0.0" ixz="0.0"
          iyy="0.000001" iyz="0.0"
          izz="0.000002"/>
    </inertial>
    </xacro:extra_module>
  <!-- end: gps -->

  <!-- 2.3  side-view  and downwards realsense t265 -->
  <xacro:extra_module name = "realsense_t265_modules_unit" parent = "link2" visible = "1"
                      model_url = "package://hydrus/urdf/mesh/ver1/sensor/realsense_t265_unit.dae">
    <origin xyz="${link_length/2 + 0.28715} 0.0 -0.04015" rpy="0 0 0"/>
    <inertial>
      <mass value = "0.123" />
      <origin xyz="${-26.37 * 0.001} ${-15.52 * 0.001} ${2.96 * 0.001}" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0001" iyz="0.0"
          izz="0.0001"/>
    </inertial>
  </xacro:extra_module>

  <!-- sensor1: side-view realsense t265 -->
  <xacro:extra_module name = "realsense1_pose_frame" parent = "realsense_t265_modules_unit" visible = "0" >
    <origin xyz="${(13.6 - 32) * 0.001} ${-19 * 0.001} ${1 * 0.001}" rpy="0 0 ${-pi/2}"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <!-- sensor2: downward realsense t265 -->
  <xacro:extra_module name = "realsense2_pose_frame" parent = "realsense_t265_modules_unit" visible = "0" >
    <origin xyz="${-174.6 * 0.001} 0 ${23 * 0.001}" rpy="0 ${pi/2} ${pi/2}"/>
    <inertial>
      <mass value = "0.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.0" ixy="0.0" ixz="0.0"
          iyy="0.0" iyz="0.0"
          izz="0.0"/>
    </inertial>
  </xacro:extra_module>

  <!-- usb-hub -->
  <joint name="link32usb_hub" type="fixed">
    <parent link="link3"/>
    <child link="usb_hub"/>
    <origin xyz="${40 * 0.001} 0 ${-100 * 0.001}" rpy="0 0 0"/>
  </joint>
  <link name="usb_hub">
    <inertial>
      <mass value = "${(16.8 + 2 * 9.3) * 0.001}" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia
          ixx="0.000002" ixy="0.0" ixz="0.0"
          iyy="0.000001" iyz="0.0"
          izz="0.000001"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.03 0.015 0.02" />
      </geometry>
      <material name="Black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
  </link>

</robot>
